const projects = [
  {
    id: "smash-it",
    name: "Smash It!",
    description:
      "Performance tracking for table tennis. This project was inspired by the competitve nature of table tennis during my web development bootcamp.",
    stack: "React, SASS, Node.js, Express.js, Knex.js, Objection.js, MySQL ",
    alt: "Smash It App",
    url: "https://smash-it.vercel.app",
    github: "https://github.com/Excelsior2021/smash-it",
  },
  {
    id: "pairs",
    name: "Pairs",
    description:
      "An interactive card game. Developed as a terminal based game with Python, then as a web application using React and now as a web application using SolidJS. Single player and multiplayer.",
    stack: "SolidJS, SASS, TypeScript, Node.js, Express.js, Socket.IO",
    alt: "Pairs App",
    url: "https://pairs-card-game.vercel.app",
    github: "https://github.com/Excelsior2021/pairs",
  },
  {
    id: "ultimate-trivia",
    name: "Ultimate Trivia",
    description:
      "A web application using the Trivia Database API. Developed in 24 hours during my web development bootcamp.",
    stack: "HTML, SASS, TypeScript, webpack",
    alt: "Ultimate Trivia App",
    url: "https://excelsior2021.github.io/ultimate-trivia",
    github: "https://github.com/Excelsior2021/ultimate-trivia",
  },
  {
    id: "view",
    name: "View Streaming App POC",
    description: "A proof of concept for a video streaming app.",
    stack: "React, SASS, TypeScript",
    alt: "View App",
    url: "https://view-web-app-client.vercel.app",
    github: "https://github.com/Excelsior2021/view-web-app-client",
  },
  {
    id: "job-listings",
    name: "Job Listings POC",
    description: "A proof of concept for a job listings app.",
    stack: "React, SASS, TypeScript, Redux Toolkit",
    alt: "Job Listings App",
    url: "https://job-listings-poc.vercel.app",
    github: "https://github.com/Excelsior2021/job-listings",
  },
  {
    id: "multi-step-form",
    name: "Multi Step Form",
    description: "A multi step form.",
    stack: "SolidJS, SASS, TypeScript",
    alt: "multi step form",
    url: "https://multi-step-form-lorem.vercel.app",
    github: "https://github.com/Excelsior2021/multi-step-form",
  },
  {
    id: "space-tourism",
    name: "Space Tourism App POC",
    description: "A proof of concept for a space torusim app.",
    stack: "React, SASS, TypeScript",
    alt: "Space Tourism App",
    url: "https://space-tourism-poc.vercel.app",
    github: "https://github.com/Excelsior2021/space-tourism",
  },
  {
    id: "veg-meals",
    name: "VegMeals",
    description: "A food ordering app.",
    stack: "React, Firebase",
    alt: "Veg Meals App",
    url: "https://excelsior2021.github.io/veg-meals",
    github: "https://github.com/Excelsior2021/veg-meals",
  },
  {
    id: "calculator",
    name: "Calculator",
    description: "An online calculator.",
    stack: "React, TypeScript",
    alt: "Calculator App",
    url: "https://excelsior2021.github.io/calculator",
    github: "https://github.com/Excelsior2021/calculator",
  },
  {
    id: "battleship",
    name: "Battleship",
    description: "An adaptation of the classic game Battleship.",
    stack: "HTML, CSS, JavaScript",
    alt: "Battleship App",
    url: "https://excelsior2021.github.io/battleship",
    github: "https://github.com/Excelsior2021/battleship",
  },
  {
    id: "target-practice",
    name: "Target Practice",
    description: "A 2D game developed in Python with the pygame library.",
    stack: "Python",
    alt: "Target Practice Python Game",
    url: "https://github.com/Excelsior2021/target-practice",
    github: "https://github.com/Excelsior2021/target-practice",
  },
]

export default projects
